### PR TITLE
Resolved issue related to slice and mut slice sizes in derive

### PR DESCRIPTION
**Pull request by LucaCappelletti94**
Not yet solved, but at least now it can be reproduced easily.

### CODE REVIEW

**Comment by vigna** [comment]
For sure I forgot to implement `FOLLOW_REFS` in the mutable version.

**Comment by LucaCappelletti94** [comment]
No, that isn't it - I have now added more tests and it is relative to how rust interprets the types in these two cases:

This fails:

https://github.com/zommiommy/mem_dbg-rs/blob/01eb8122cd83b7cc6bfc024a16e85738c6de7548/mem_dbg/tests/test_mem_size.rs#L446-L468

This does not:

https://github.com/zommiommy/mem_dbg-rs/blob/01eb8122cd83b7cc6bfc024a16e85738c6de7548/mem_dbg/tests/test_mem_size.rs#L473-L497

The only difference is that I specify the type in the mem_size call in the latter. I think it is an issue in the derive, as the type is not explicitly specified in several points.

**Comment by vigna** [comment]
Could you please write the tests following the guidelines, i.e., left is actual, right is expected? Consistency really helps in reading the output (disclaimer: some of the existing tests might not follow the guidelines). 

Presently the text comment is plainly wrong, as it mention first mutable, then non-mutable, but then the two arguments are in reverse order.

I would reverse the first two arguments, and leave the third as it is, but without further arguments. So it's actual vs expected and the text explains, in the correct order, what is actual (left) and expected (right).

**Comment by LucaCappelletti94** [comment]
Honestly, I wrote several of these tests yesterday at 2 AM, I need to clean them up, and I will do that soon. Anyway, found the bug and squashed it! It was a thing in the derive.

**Comment by vigna** [comment]
Amazing!

**Comment by vigna** [comment]
Great, can I merge?

**Comment by LucaCappelletti94** [comment]
Right now the Cargo.toml of the `mem_dbg` crate refers to the local path to get the current `mem_dbg-derive` crate so that the tests are now passing. Just recall to change that back to the new crate version before publishing.

**Comment by vigna** [comment]
So the issue was that in the derive code the compiler was selecting the wrong type?

**Comment by LucaCappelletti94** [comment]
I am not sure whether it was behaving as expected or not, but basically for `&T` it was called mem_size of `T`, while for `&mut T` it was calling mem size of `&mut T`. This way I am forcing it to call mem_size of `&T` when the type is `&T`

**Comment by vigna** [comment]
I see here a much more general problem that must be documented (we should probably have a look at what other crates do). When you invoke `mem_size` on a shared reference, the compiler inserts a silent dereferencing and returns the mem_size of the pointed structure. When you invoke `mem_size` on an exclusive reference, it returns the size of the reference. This happens at the top level, too, which is disorienting. The fix in the derive solves the issue for references within complex types, but the problem at the top level is still there.

**Comment by vigna** [comment]
I can confirm that all crates we compare with have the same problem. I guess it is unavoidable. That was a good catch!

**Comment by vigna** [comment]
The problem is (as it was likely) shared by `MemDbg`.

**Comment by LucaCappelletti94** [comment]
@vigna I will look into that in another PR, could you take a look at PR #5 ? I had made an error in the current PR #4

**Comment by vigna** [comment]
Yes, it's much less problematic (it's a print, in the end) but stuff like that
```
                    #field_idx => self.#field_ident._mem_dbg_depth_on(_memdbg_writer, _memdbg_total_size, _memdbg_max_depth, _memdbg_prefix, Some(#field_ident_str), i == n - 1, padded_size, _memdbg_flags)?,
```
using the identifier have the same problem.

**Comment by LucaCappelletti94** [comment]
> Yes, it's much less problematic (it's a print, in the end) but stuff like that
> 
> ```
>                     #field_idx => self.#field_ident._mem_dbg_depth_on(_memdbg_writer, _memdbg_total_size, _memdbg_max_depth, _memdbg_prefix, Some(#field_ident_str), i == n - 1, padded_size, _memdbg_flags)?,
> ```
> 
> using the identifier have the same problem.

Currently fixing exactly that

**Pull request merged**
